config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home_page#index"

  get "home_page/index"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "register", to: "users#new"

  resources :bids, only: %i[index]

  resources :users, except: %i[new]
  
  resources :products do
    resources :bids, only: %i[new create edit update]
  end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
    def index
    end
end

app/views/home_page/index.html.erb
<main class="home">
  <header>
    <nav>
      <div class="logo">
        <img src="https://www.linkpicture.com/q/click_1.png"></div>
      <div class="options">
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Contact</li>
          <li>News</li>
        </ul>
      </div>
      <div class="buttons">
        <%= link_to "Log in", login_path %>
        <%= link_to "Sign up", register_path %>
      </div>
    </nav>
  </header>
  <section>
    <div class="left">
      <div class="slogan">Biddin’ Business.</div>
      <div class="text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua in hac habitasse
        platea.
      </div>
      <%= link_to "Get Started", register_path %>
    </div>
    <div class="right">
      <img src="https://www.linkpicture.com/q/bids-removebg-preview.png">
    </div>
  </section>
</main>