config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home_page#index"

  get "home_page/index"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "register", to: "users#new"

  resources :bids, only: %i[index]

  resources :users, except: %i[new]
  
  resources :products do
    resources :bids, only: %i[new create edit update]
  end
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :amount, presence: true

  after_validation :bid_amount

  def bid_amount
    if self.amount && self.product && self.amount < self.product.starting_bid_price
      errors.add(:amount, "should be greater than or equal to #{self.product.starting_bid_price}")
    end
  end

  scope :bid_winner, ->() { find_by(amount: self.maximum(:amount)) }
  scope :lowest_bid, ->() { minimum(:amount) }
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_bid, only: %i[ edit update ]
  before_action :set_product, only: %i[new create edit update]
  before_action :authenticate_admin, only: %i[ index ]
  before_action :restrict_admin, only: %i[new create edit update]

  def index
    @bids = Bid.all
  end

  def new
    @bid = @product.bids.build
    @lowest_bid = @product.bids.lowest_bid
  end

  def edit
    @lowest_bid = @product.bids.lowest_bid
  end

  def create
    @bid = @product.bids.build(bid_params)
    @bid.user_id = current_user.id

    if @bid.save
      respond_to do |format|
        format.html { redirect_to products_path }
        format.turbo_stream { flash.now[:notice] = "Bid placed!" }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @bid.update(bid_params)
      respond_to do |format|
        format.html { redirect_to product_path(@bid.product) }
        format.turbo_stream { flash.now[:notice] = "Bid updated!" }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end

  def set_bid
    @bid = Bid.find(params[:id])
  end

  def bid_params
    params.require(:bid).permit(:amount)
  end
end

app/views/bids/_form.html.erb
<%= form_with(model: bid, url: url) do |form| %>
  <%= render "shared/errors", object: bid %>
  <div>
    <%= form.number_field :amount,
                      placeholder: "#{bid.product.starting_bid_price} or higher",
                      style: "margin-top: 10px" %>
  </div>
  <div>
    <%= form.submit action_name == "new" ? "Place a Bid" : "Update" %>
  </div>
<% end %>

app/views/bids/create.turbo_stream.erb
<%= turbo_stream.replace @bid.product %>
<%= turbo_stream.update 'modal', '' %>
<%= turbo_stream.prepend("flash", partial: "layouts/flash") %>

app/views/bids/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <main class="new-bid">
    <div class="container">
      <div class="top">
        <div>
          <div class="title">Update Bid</div>
          <div class="min">
            You must bid at least
            <%= number_to_currency(
              @bid.product.starting_bid_price,
              unit: "₱",
              strip_insignificant_zeros: true
            ) %></div>
          <% if @lowest_bid.present? %>
            <div class="lowest">
              Current lowest bid:
              <%= number_to_currency(@lowest_bid, unit: "₱", strip_insignificant_zeros: true) %>
            </div>
          <% end %>
        </div>
        <%= image_for(@bid.product) %>
      </div>
      <%= render "form", bid: @bid, url: product_bid_path(@product, @bid) %>
      <%= link_to "Close", :back, class: "back" %>
    </div>
  </main>
<% end %>

app/views/bids/index.html.erb
<main class="bids">
  <%= render "layouts/nav" %>
  <section>
    <div class="top">
      <div class="title">All Bids</div>
    </div>
    <div class="table">
      <div class="th">
        <div>Date</div>
        <div>Time</div>
        <div>Product Name</div>
        <div>Minimum Bid</div>
        <div>Status</div>
        <div>Bidder</div>
        <div>Bid Placed</div>
      </div>
      <% @bids.order(updated_at: :desc).each do |bid| %>
        <div class="data">
          <div><%= bid.created_at.strftime("%b %d, %Y") %></div>
          <div><%= bid.created_at.strftime("%I:%M:%S %p") %></div>
          <div><%= bid.product.name %></div>
          <div><%= number_to_currency(
              bid.product.starting_bid_price,
              unit: "₱",
              strip_insignificant_zeros: true
            ) %></div>
          <% if bid.product.active? %>
            <div class="active">
              ongoing
            </div>
          <% else %>
            <div class="inactive">
              ended
            </div>
          <% end %>
          <div><%= bid.user.full_name %></div>
          <div><%= number_to_currency(bid.amount, unit: "₱", strip_insignificant_zeros: true) %></div>
        </div>
      <% end %>
    </div>
  </section>
</main>

app/views/bids/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <main class="new-bid">
    <div class="container">
      <div class="top">
        <div>
          <div class="title">Place a Bid</div>
          <div class="min">
            You must bid at least
            <%= number_to_currency(
              @bid.product.starting_bid_price,
              unit: "₱",
              strip_insignificant_zeros: true
            ) %></div>
          <% if @lowest_bid.present? %>
            <div class="lowest">
              Current lowest bid:
              <%= number_to_currency(@lowest_bid, unit: "₱", strip_insignificant_zeros: true) %>
            </div>
          <% end %>
        </div>
        <%= image_for(@bid.product) %>
      </div>
      <%= render "form", bid: @bid, url: product_bids_path(@product) %>
      <%= link_to "Close", :back, class: "back" %>
    </div>
  </main>
<% end %>

app/views/bids/update.turbo_stream.erb
<%= turbo_stream.replace @bid.product %>
<%= turbo_stream.update 'modal', '' %>
<%= turbo_stream.prepend("flash", partial: "layouts/flash") %>