config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home_page#index"

  get "home_page/index"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "register", to: "users#new"

  resources :bids, only: %i[index]

  resources :users, except: %i[new]
  
  resources :products do
    resources :bids, only: %i[new create edit update]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :bids, dependent: :destroy

  validates_presence_of :description, :starting_bid_price
  validates :name, presence: true, length: { in: 1..20 }

  validates_numericality_of :starting_bid_price, greater_than: 0

  enum bidding_status: { expired: 0, active: 1 }

  before_validation :set_default_expiration
  before_validation :expiration_date_cannot_be_in_the_past, on: :create

  def set_default_expiration
    self.bidding_expiration ||= 7.days.from_now
  end

  def expiration_date_cannot_be_in_the_past
    if self.bidding_expiration.present? && bidding_expiration < DateTime.current
      errors.add(:bidding_expiration, "can't be in the past")
    end
  end

  def is_resumable?
    self.bidding_expiration < DateTime.current
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_admin, except: %i[index]

  def index
    @products = Product.order(created_at: :desc)
  end
  
  def show
  end

  def new
    @product = current_user.products.build
  end

  def edit
  end

  def create
    @product = current_user.products.build(product_params)

    if @product.save
      respond_to do |format|
        format.html { redirect_to products_path }
        format.turbo_stream { flash.now[:notice] = "Product added!" }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @product.bidding_status = "active" if product_params[:bidding_expiration] && product_params[:bidding_expiration].to_datetime.future?
    if @product.update(product_params)
      respond_to do |format|
        format.html { redirect_to products_path }
        format.turbo_stream { flash.now[:notice] = "Product updated!" }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_path }
      format.turbo_stream { flash.now[:notice] = "Product deleted!" }
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :starting_bid_price, :bidding_expiration, :bidding_status)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def image_for(product)
    dicebear_seed = Digest::MD5::hexdigest(product.name)
    dicebear_url = "https://api.dicebear.com/5.x/shapes/svg?seed=#{dicebear_seed}"
    image_tag(dicebear_url, alt: product.name, class: "dicebear_avatars")
  end
end

app/views/products/_admin.html.erb
<div class="admin-buttons">
  <% if product.active? %>
    <%= form_for product do |f| %>
      <%= f.hidden_field :bidding_status, value: "expired" %>
      <%= f.submit "Stop", class: "stop" %>
    <% end %>
  <% else %>
    <%= form_for product do |f| %>
      <%= f.hidden_field :bidding_status, value: "active" %>
      <%= f.submit "Resume",
               data: {
                 disable_with: product.is_resumable?
               },
               class: "resume" %>
    <% end %>
  <% end %>
  <% if product.expired?  %>
    <div class="edit disabled">
      <%= link_to "Edit", edit_product_path(product), data: { turbo_frame: "modal" } %>
    </div>
  <% else %>
    <div class="edit">
      <%= link_to "Edit", edit_product_path(product), data: { turbo_frame: "modal" } %>
    </div>
  <% end %>
  <div class="delete">
    <%= link_to "Delete",
    product,
    data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
  </div>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <%= render "shared/errors", object: product %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
  <% unless product.bids.any? %>
    <div>
      <%= form.label :starting_bid_price, style: "display: block" %>
      <%= form.number_field :starting_bid_price %>
    </div>
  <% end %>
  <div>
    <%= form.label :bidding_expiration, style: "display: block" %>
    <%= form.datetime_local_field :bidding_expiration %>
  </div>
  <div>
    <%= form.submit action_name == "new" ? "Create" : "Update" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<%= turbo_frame_tag product do %>
  <div class="container">
    <div class="name">
      <div class="left">
        <div class="title">
          <%= product.name %>
        </div>
        <div class="min">
          Minimum bid:
          <span class="price">
            <%= number_to_currency(
              product.starting_bid_price,
              unit: "₱",
              strip_insignificant_zeros: true
            ) %>
          </span>
        </div>
         
    
        <div class="status">
          <% if product.active? %>
            <div class="active">
              ongoing
            </div>
          <% else %>
            <div class="inactive">
              ended
            </div>
          <% end %>
        </div>
      </div>
      <%= image_for(product) %>
    </div>
     
    <div class="description">
      <div id="details">Details:</div>
      <div><%= product.description %></div>
    </div>
    <% unless current_user.user? %>
      <div class="bidder-count">
        <% if product.bids.any? %>
          <%= link_to product_path(product), data: {turbo_frame: "modal"} do %>
            <%= pluralize(product.bids.count, "bidder") %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  
    <div class="expiry">
      <% if product.active? %>
        Bidding ends on
        <strong>
          <%= product.bidding_expiration.strftime("%b %d, %Y") %>
        </strong>
      <% elsif product.expired? && product.bids.any? %>
        <div class="winner">
          Winner:
          <strong>
            <%= product.bids.bid_winner.user.full_name %>
            🎉
          </strong>
        </div>
      <% else %>
        No bidders.
      <% end %>
    </div>

    <% bid = product.bids.find_by(user_id: current_user.id) %>
    <% if bid %>
      <div class="amount-placed">
        Placed
        <%= number_to_currency(bid.amount, unit: "₱", strip_insignificant_zeros: true) %>
      </div>
    <% end %>
    
    <div class="buttons">
      <% if current_user.admin? %>
        <%= render "products/admin", product: product %>
      <% else %>
        <div class="user-button">
          <% if bid && product.active? %>
            <%= link_to "Update Bid", edit_product_bid_path(product, bid), data: { turbo_frame: "modal" }, class: "update-bid" %>
          <% elsif !bid && product.active? %>
            <%= link_to "Place a Bid",
            new_product_bid_path(product),
            data: {
              turbo_frame: "modal"
            } %>
          <% elsif bid && product.expired? || product.expired? %>
          <div class="ended">
          The bidding has ended.
          <% if product.expired? && product.bids.any? && product.bids.bid_winner.user == current_user %>
          You won!
          <% end %>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/products/create.turbo_stream.erb
<%= turbo_stream.prepend "products", @product %>
<%= turbo_stream.update 'modal', '' %>
<%= turbo_stream.prepend("flash", partial: "layouts/flash") %>

app/views/products/destroy.turbo_stream.erb
<%= turbo_stream.remove @product %>
<%= turbo_stream.prepend("flash", partial: "layouts/flash") %>

app/views/products/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <main class="product-modal">
    <div class="container">
      <div class="top">
        <div class="title">Edit Product</div>
      </div>
      <%= render "form", product: @product %>
      <%= link_to "Close", :back, class: "back" %>
    </div>
  </main>
<% end %>

app/views/products/index.html.erb
<main class="products">
  <%= render "layouts/nav" %>
  <section>
    <div class="top">
      <div class="title">All Products</div>
      <% if current_user.admin? %>
        <%= link_to "+ Add New", new_product_path, data: { turbo_frame: "modal" } %>
      <% end %>
    </div>
    <%= turbo_frame_tag "products", id: "products" do %>
      <%= render @products %>
    <% end %>
  </section>
</main>
<%= turbo_frame_tag "modal" %>

app/views/products/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <main class="product-modal">
    <div class="container">
      <div class="top">
        <div class="title">Add Product</div>
      </div>
      <%= render "form", product: @product %>
      <%= link_to "Close", :back, class: "back" %>
    </div>
  </main>
<% end %>

app/views/products/show.html.erb
<%= turbo_frame_tag "modal" do %>
  <main class="show-bidder">
    <div class="container">
      <div class="name">
        <%= @product.name %>
      </div>
      <div class="title">Bidders</div>
      <div class="grid">
        <div class="header">
          <div class="rank">Rank</div>
          <div class="user-name">Name</div>
          <div class="amount">Amount</div>
        </div>
        <div class="data">
          <% @product.bids.order(amount: :desc).each do |bidder| %>
          <div> <%= @product.bids.order(amount: :desc).find_index(bidder) + 1%></div>
            <div>
              <%= bidder.user.full_name %></div>
            <div><%= number_to_currency(bidder.amount, unit: "₱", strip_insignificant_zeros: true) %>
            </div>
          <% end %>
        </div>
      </div>
      <%= link_to "Close", :back, class: "back" %>
    </div>
  </main>
<% end %>

app/views/products/update.turbo_stream.erb
<%= turbo_stream.replace @product %>
<%= turbo_stream.update 'modal', '' %>
<%= turbo_stream.prepend("flash", partial: "layouts/flash") %>