config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home_page#index"

  get "home_page/index"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "register", to: "users#new"

  resources :bids, only: %i[index]

  resources :users, except: %i[new]
  
  resources :products do
    resources :bids, only: %i[new create edit update]
  end
end

app/views/layouts/_flash.html.erb
<turbo-frame id="flash">
  <div id="flash">
    <% flash.each do | message_type, message | %>
      <div class="<%= message_type %>">
        <%= message %>
      </div>
    <% end %>
  </div>
</turbo-frame>

app/views/layouts/_nav.html.erb
<header>
  <nav>
    <div class="logo">
      <img src="https://www.linkpicture.com/q/click_1.png">
    </div>
    <% if current_user.admin? %>
      <ul>
        <li><%= link_to "Products",
          products_path,
          class: controller_name == "products" ? "clicked" : "" %></li>
        <li>
          <%= link_to "Users",
          users_path,
          class: controller_name == "users" && action_name == "index" ? "clicked" : "" %>
        </li>
        <li>
          <%= link_to "Bids", bids_path, class: controller_name == "bids" ? "clicked" : "" %>
        </li>
        <li>
          <%= link_to "Log out", logout_path, data: { turbo_method: :delete } %>
        </li>
      </ul>
    <% else %>
      <ul>
        <li><%= link_to "Products",
          products_path,
          class: controller_name == "products" ? "clicked" : "" %></li>
        <li><%= link_to "Bids",
          user_path(current_user),
          class: controller_name == "users" && action_name == "show" ? "clicked" : "" %>
        </li>
        <li>
          <%= link_to "Settings",
          edit_user_path(current_user),
          class: controller_name == "users" && action_name == "edit" ? "clicked" : "" %>
        </li>
        <li>
          <%= link_to "Log out", logout_path, data: { turbo_method: :delete } %>
        </li>
      </ul>
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClickBids</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
      rel="stylesheet"
    >
    <script src="https://kit.fontawesome.com/854e38c6b1.js" crossorigin="anonymous"></script>
    <link
       rel="icon"
       type="image/x-icon"
       href="https://www.linkpicture.com/q/logo_786.png"
     >
  </head>
  <body>
    <%= yield %>
    <%= render "layouts/flash" %>
  </body>
</html>